### ISSUE TITLE
Collision with rdkit

### ISSUE THREAD

**Issue by isty2e** [molinfo-vienna/CDPKit#19] opened 2024-08-28 13:14 UTC
## Statement of the problem

With recent versions of rdkit, when `from rdkit import Chem` is executed before importing CDPKit, CDPKit becomes broken for unknown reasons (maybe due to namespace collision?). This does not happen for rdkit < 2023.

An example of the error reproduced in python REPL:

```
>>> from rdkit import Chem
>>> import CDPL.Chem as CDPChem
>>> reader = CDPChem.MoleculeReader("an-arbitrary-path-to-sdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    MoleculeReader.__init__(MoleculeReader, str)
did not match C++ signature:
    __init__(_object* self, std::istream {lvalue} is, CDPL::Base::DataFormat fmt)
    __init__(_object* self, std::istream {lvalue} is, std::string fmt)
    __init__(_object* self, std::string file_name, CDPL::Base::DataFormat fmt, std::_Ios_Openmode mode=CDPL.Base._base.OpenMode(12))
    __init__(_object* self, std::string file_name, std::string fmt, std::_Ios_Openmode mode=CDPL.Base._base.OpenMode(12))
    __init__(_object* self, std::string file_name, std::_Ios_Openmode mode=CDPL.Base._base.OpenMode(12))
>>> exit()
```

## To reproduce:

First, create a conda env on a linux system (by the way, `numpy < 2` is required for pip installation of `cdpkit`, but it is not specified neither in `pyproject.toml` nor `setup.py`):

```bash
mamba create -n cdpkit-test python=3.10
mamba activate cdpkit-test
mamba install rdkit "numpy < 2"
pip install cdpkit
```

This works:

```python
import CDPL.Chem as CDPChem

reader = CDPChem.MoleculeReader("any-arbitrary-string")
```

but this does not:

```python
from rdkit import Chem
import CDPL.Chem as CDPChem

reader = CDPChem.MoleculeReader("any-arbitrary-string")
```

**Comment by seidelt** [comment] 2024-08-29 10:42
Many thanks for pointing me to the numpy version issue! Has now been fixed by adding a version specifier to the numpy entry in pyproject.toml

Regarding the collision:
I followed your steps but could not reproduce the observed problem. Both code snippets execute without producing errors!!

**Comment by isty2e** [comment] 2024-08-29 11:36
Huh, that's strange. Presumably it is dependent on the system environment or something. I will try to reproduce it in a Docker container so a better reproducibility is guaranteed, but I'm afraid I don't have time to do that for now.

**Comment by seidelt** [comment] 2024-08-29 11:46
Many thanks for your efforts!
I did a completely fresh installation of Miniforge, maybe this information is useful for you.

**Comment by stefdoerr** [comment] 2024-09-12 07:37
Hi I am able to reproduce it consistently. Under Ubuntu 22.04 do the following:
```
mamba create -n cdpkit_rdkit
mamba activate cdpkit_rdkit
mamba install python=3.10 rdkit "numpy<2" -c conda-forge
pip install cdpkit
```
Then run the following in a python console
```py
>>> from rdkit import Chem
>>> import CDPL.Chem as CDPChem
>>> CDPChem.MoleculeReader("/home/sdoerr/Downloads/00-All-1700.sdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    MoleculeReader.__init__(MoleculeReader, str)
did not match C++ signature:
    __init__(_object* self, std::istream {lvalue} is, CDPL::Base::DataFormat fmt)
    __init__(_object* self, std::istream {lvalue} is, std::string fmt)
    __init__(_object* self, std::string file_name, CDPL::Base::DataFormat fmt, std::_Ios_Openmode mode=CDPL.Base._base.OpenMode(12))
    __init__(_object* self, std::string file_name, std::string fmt, std::_Ios_Openmode mode=CDPL.Base._base.OpenMode(12))
    __init__(_object* self, std::string file_name, std::_Ios_Openmode mode=CDPL.Base._base.OpenMode(12))
```
Trying the inverse causes a segmentation fault
```py
>>> import CDPL.Chem as CDPChem
>>> from rdkit import Chem
[1]    246425 segmentation fault (core dumped)  python
```

This happens with rdkit 2024.03.5 and some previous versions which I've tested.
It can be fixed by downgrading rdkit to version 2022.09.1

It can be reproduced consistently on other machines (I had it happen on Github Actions as well as two local machines, it's very consistent, here are some [jobs](https://github.com/Acellera/moleculekit/actions/runs/10806592666/job/29975698832) all crashing with this  issue, although the logs are huge and confusing but you can search for `Boost.Python.ArgumentError`)

**Comment by stefdoerr** [comment] 2024-09-12 07:39
I attach you here also the conda env file if you want to install directly from this to reproduce
[cdpkit_rdkit.zip](https://github.com/user-attachments/files/16975275/cdpkit_rdkit.zip)

**Comment by seidelt** [comment] 2024-09-12 08:38
Hi Stefan,

many thanks for having a look into this issue! However, again, I was not able to reproduce the error when following your steps. Reversing the order of imports also did not result in a segmentation fault.
I am not a conda user and therefore I had to install miniforge from scratch (as I did in my initial attempt to reproduce the errors, but now on a different Linux installation). 
If possible try to do the same and report if there are still errors. Or, alternatively, try to upgrade your miniforge installation to the latest version (which I have used).

PS: My environment file after following your steps is exactly the same as yours (except the last line starting with 'prefix')

**Comment by seidelt** [comment] 2024-09-12 12:08
Hi Stefan,

thanks for also looking into this! I was now able to reproduce the errors. During my first attempt I didn't recognize that my PYTHONPATH variable was still pointing to a compiled development version of the CDPKit CDPL python bindings which was then imported instead of the 1.1.1 release version installed via pip. However, this mistake helped me to identify the cause of the reported problems:
The 1.1.1 release of the CDPKit python bindings and the RDKit package installed via conda are both compiled against the same boost .python version (1.84.0). RDKit as well as CDPKit bring their own copies of the boost .python library and usually the dynamic linker will load them. However, the linker only loads the private copy if the linked against boost.python library version has not yet been loaded. When RDKit gets imported its private copy of boost.python 1.84.0 is loaded - as expected. But during the subsequent import of the CDPL.Chem package the dynamic linker does not load the CDPL provided copy anymore since it is already present. Although both boost.python libraries are of exactly the same version they seem to be incompatible and lead to the observed problems.

Fixes:
- Compile and install the latest CDPKit source package deposited on PyPI within the conda environment. This will lead to a binary compatible with the conda installed RDKit - that works, tested it! (see https://cdpkit.org/installation)
- Install the latest stable full-featured CDPKit binary release which is linked against an older boost.python version (see https://github.com/molinfo-vienna/CDPKit/releases/tag/v1.1.1). PYTHONPATH then needs to be set (see https://cdpkit.org/installation).

For future binary releases deposited on PyPI  I will see if I can set the version of the private boost.python copy to something that is valid but does not exist. This tweak should then fix the problem by forcing the dynamic linker to always load the installed private copy....

**Comment by stefdoerr** [comment] 2024-09-12 12:47
Wow, thanks for the deep investigation!
I hope the next versions fix this then. I will try the source installation from PyPI and see if it works. Btw you have a minor typo on the installation command on that page. It says `pip install cpkit --no-binary :all:` but is missing the `d` in the package name.

**Comment by stefdoerr** [comment] 2024-10-10 06:32
Do you have an ETA for the next release which will fix the rdkit collision?

**Comment by seidelt** [comment] 2024-10-10 09:16
I am planning to release an official V1.2.0 before the end of 2024. However, I will try to find some time in the next two weeks to release a 1.2.0 pre-version (for Linux only) on PyPI. This pre-version will not yet provide all features that I planned for 1.2.0 but will at least fix the RDKit and nasty NumPy2 issue for Linux users.

**Comment by mainguyenanhvu** [comment] 2024-10-19 06:27
@seidelt If you need to support, I can join hands to do because I am really keen on your codebase. I found that because of the conflicts when importing rdkit along with CDPkit, my code have to split into files instead of combining into one file.

**Comment by seidelt** [comment] 2024-10-22 12:17
As promised, I made Linux wheels for a CDPKit 1.2.0 pre-release available on PyPI. The RDKit as well as NumPy2 compatibility issues are gone with this version!

The CDPKit 1.2.0 pre-release can be installed as follows:
$ pip install CDPKit==1.2.0.dev1

Please let me know whether the new version also works for your setup!

**Comment by isty2e** [comment] 2024-10-23 01:44
Tested on a fresh conda environment.

This works without any problem:

```python
from rdkit import Chem
import CDPL.Chem as CDPChem

reader = CDPChem.MoleculeReader("any-arbitrary-string")
```

But when the import order is changed like below,

```python
import CDPL.Chem as CDPChem
from rdkit import Chem
```

The following error occurs:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/conda/envs/cdpkit-test/lib/python3.10/site-packages/rdkit/Chem/__init__.py", line 16, in <module>
    from rdkit.Chem import rdchem
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /path/to/conda/envs/cdpkit-test/lib/python3.10/site-packages/rdkit/Chem/../../../../libboost_serialization.so.1.86.0)
```

**Closed** 2024-10-26 06:31 UTC
Labels: unexpected behaviour
