### ISSUE TITLE
Upgrade NumPy 1x to 2x

### ISSUE THREAD

**Issue by mainguyenanhvu** [molinfo-vienna/CDPKit#21] opened 2024-10-18 09:21 UTC
When I import CDPL ConfGen `import CDPL.ConfGen as CCfGen`, it raises a warning:
```
    import CDPL.ConfGen as CCfGen
  File "/home/vumna/anaconda3/envs/biotools_py39/lib/python3.9/site-packages/CDPL/ConfGen/__init__.py", line 27, in <module>
    import CDPL.ForceField
  File "/home/vumna/anaconda3/envs/biotools_py39/lib/python3.9/site-packages/CDPL/ForceField/__init__.py", line 27, in <module>
    import CDPL.Chem
  File "/home/vumna/anaconda3/envs/biotools_py39/lib/python3.9/site-packages/CDPL/Chem/__init__.py", line 28, in <module>
    import CDPL.Math
  File "/home/vumna/anaconda3/envs/biotools_py39/lib/python3.9/site-packages/CDPL/Math/__init__.py", line 29, in <module>
    from ._math import *
Traceback (most recent call last):
  File "/home/vumna/anaconda3/envs/biotools_py39/lib/python3.9/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getatt
r__
    raise ImportError(msg)
ImportError:

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

I think we should upgrade codes to use NumPy2x which is compatible with python 3.9 or higher.

**Comment by seidelt** [comment] 2024-10-20 06:21
This is a duplicate of issue #19

**Closed** 2024-10-20 06:21 UTC
